version: '3.7'

services:
  twitter:
    build: ./twitter
    restart: always
    ports:
      - 8081:80
  youtube:
    build: ./youtube
    restart: on-failure
    ports:
      - 8083:80
  instagram:
    build: ./instagram
    restart: always
    ports:
      - 8084:80
  reddit:
    build: ./reddit
    restart: always
    ports:
      - 8085:80
  middleware:
    build: ./middleware/WebApplication1
    restart: always
    ports:
      - 8080:80
      
  dashboard:
    build: ./dashboard
    restart: always
    ports:
      - 80:80
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=TelegrafPassword
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  telegraf:
    image: telegraf
    volumes:
      - ./monitoring/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb


  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.example.com
      - GF_SECURITY_ADMIN_PASSWORD=GrafanaPassword
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,raintank-worldping-app,jdbranham-diagram-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=example.com
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana:
  influxdb:
    
